enableGlobalCache: true
# size of cache is not concern if you aren't using zero-installs
compressionLevel: 0

nodeLinker: node-modules
nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
