name: "Feature Request"
description: "Request new Feature to adapter/snap"
title: "[feature]: "
labels: ["enhancement", "unconfirmed"]
assignees:
 - BeroBurny
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summary of the context why you want to do this.
      placeholder: Tell us!!!
    validations:
      required: true
  - type: textarea
    id: story
    attributes:
      label: Expected behavior / User Story
      description: Describe how you expect this improvement to behave once in production.
      placeholder: Users will feel safe...
    validations:
      required: true
  - type: textarea
    id: completion
    attributes:
      label: Completion
      placeholder: When i press that want that to do
    validations:
      required: true
