name: ci
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          cache: yarn
          node-version: '16.x'
      - run: yarn install --immutable
      - name: Run linter
        run: yarn run lint
      - name: Update Manifest for renovate
        if: github.event.pull_request.user.login == 'renovate'
        run: |
          yarn run manifest

          git config --global user.name "Renovate Bot"
          git config --global user.email "bot@renovateapp.com"

          git add -A
          git commit -m "chore: update metamask manifest"
          git push
      - name: Build
        run: yarn run build
      - uses: tj-actions/verify-changed-files@v9
        id: verify-changed-files
        with:
          files: |
             packages/snap/snap.manifest.json
      - name: Check if snap manifest updated
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Snap manifest not updated: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1
      - name: Run tests
        run: yarn run test
